In [38]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head(4)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5


In [9]:
df.fuel_type.nunique()

3

In [15]:
df.isnull().any().sum()

np.int64(2)

In [17]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

In [18]:
df.horsepower.median()

np.float64(254.0)

In [22]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [26]:
new_df = df
new_df.horsepower = new_df.horsepower.fillna(252)

In [27]:
new_df.horsepower.median()

np.float64(252.0)

In [33]:
X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [41]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [44]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [47]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [48]:
w.sum()

np.float64(0.36919696904925486)