In [4]:
import numpy as np

## Vector-vector Multiplication (Dot product)

In [36]:
u = np.array([2, 4, 5, 6])
u.shape

(4,)

In [37]:
v = np.array([1, 0, 0, 2])
v.shape

(4,)

In [38]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [39]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [40]:
u.dot(v)

np.int64(14)

## Matrix-vector Multiplication

In [41]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U.shape

(3, 4)

In [42]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [43]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [44]:
U.dot(v)

array([14,  5,  5])

## Matrix-matrix Multiplication

In [45]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])
V.shape

(4, 3)

In [61]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, V[:, i])
        result[:, i] = Uvi

    return result

In [62]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [60]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [70]:
I = np.eye(3)

In [71]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [72]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Matrix Inverse

In [74]:
Vs = V[[0, 1, 2]] # Take first 3 rows of V
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [75]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [76]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])