In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1, 2, 3, 5])

In [8]:
a[2]

np.int64(3)

In [9]:
a[2] = 10

In [10]:
a[2]

np.int64(10)

In [12]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [15]:
np.zeros((5, 2)) # 1st row, 2nd column

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
n[0][1]

np.int64(2)

In [20]:
n[:, 1]

array([2, 5])

In [21]:
n[:, 1] = [3, 6]

In [22]:
n

array([[1, 3, 3],
       [4, 6, 6]])

In [23]:
np.random.rand(5, 2)

array([[0.65235435, 0.67105558],
       [0.57238082, 0.43122872],
       [0.36103548, 0.70745625],
       [0.74645983, 0.83176874],
       [0.8747995 , 0.88023051]])

In [24]:
# psuedo random

In [26]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [27]:
np.random.seed(2)
np.random.randn(5, 2) # sample from standard normal distribution -1 - 1

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [28]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a * 10

array([ 0, 10, 20, 30, 40])

In [38]:
b = [2, 2, 3, 4, 3]

In [39]:
a + b

array([2, 3, 5, 7, 7])

In [40]:
a > b

array([False, False, False, False,  True])

In [41]:
a[a > b] # Return elements of a where condition is true

array([4])

In [42]:
a.min()

np.int64(0)

In [43]:
a.mean()

np.float64(2.0)

In [44]:
a.std()

np.float64(1.4142135623730951)